### ISSUE TITLE
Sorry

### ISSUE THREAD

**Issue by KendallDoesCoding** [FahimFBA/FahimFBA#10]
Hi,

I'm sorry you got removed without any notice, Adarsh removed many people for no reason yesterday, even I feel the same as you.

![image](https://user-images.githubusercontent.com/84712013/184530809-23c6f719-6162-40c7-aa7a-029fa07a2264.png)

**Comment by KendallDoesCoding** [comment]
@FahimFBA Waiting for your reply.

**Comment by FahimFBA** [comment]
I got that. Thanks for letting me know. If your concern was about informing me about the situation, then I have understood the fact. Therefore, I am closing the issue. However, if you need to discuss anything personally, then I prefer reaching out to me through Twitter or LinkedIn.
Thank you.

**Comment by KendallDoesCoding** [comment]
Glad you got that!

I dmed you on discord.
