### ISSUE TITLE
Unfollowed?

### ISSUE THREAD

**Issue by KendallDoesCoding** [FahimFBA/FahimFBA#11]
Hi,

Why did you unfollow me. I'm not the one that removed you from the organization bro, why would I?

@adarsh-jaiss did it, he removed me too, seriously.

**Comment by FahimFBA** [comment]
Sorry to break it down to you, @KendallDoesCoding, I don't even remember following you once. Some weird thing is happening to me suddenly.

**Comment by KendallDoesCoding** [comment]
> Sorry to break it down to you, @KendallDoesCoding, I don't even remember following you once. Some weird thing is happening to me suddenly.

Hi, you did follow me? I reached out to you from there. I am not involved with you being removed from Collab-Community, please refer to #10.

**Comment by FahimFBA** [comment]
Fixed this issue with #10

**Comment by KendallDoesCoding** [comment]
Hi, Sorry. You didn't follow me but contributed to a repo I was managing - https://github.com/TechStudent10/heroku-portfolio/pull/16 and I saw your profile was interesting so I followed you and then invited you to Collab-Community when we were looking for members.

I didn't know how Adarsh was at that time, now I have learnt :(

**Comment by FahimFBA** [comment]
It's okay. Thanks for the concern.
