### ISSUE TITLE
Twitter/X should open the twitter page in a new tab

### ISSUE THREAD

**Issue by FahimFBA** [FahimFBA/FahimFBA#19]
### Description

When we click on the Twitter/x button, it opens on the existing page, but it shouldn't happen like that. It should open a new page whenever anyone clicks on that.

### Screenshots

![image](https://github.com/FahimFBA/FahimFBA/assets/64195132/b98c6549-374d-4122-9105-5409aa1bfae4)

**Comment by sinapy** [comment]
can't really make any changes to this repository. Seems to not have the permission

> <a href="https://twitter.com/intent/follow?screen_name=Fahim_FBA" target="blank">
`<a href="https://twitter.com/intent/follow?screen_name=Fahim_FBA" target="_blank">`

Just add a underscore before "blank"

**Comment by sinapy** [comment]
sorry for my previous response. Seems that this is not possible:
https://stackoverflow.com/questions/41915571/open-link-in-new-tab-with-github-markdown-using-target-blank

**Comment by FahimFBA** [comment]
> sorry for my previous response. Seems that this is not possible: https://stackoverflow.com/questions/41915571/open-link-in-new-tab-with-github-markdown-using-target-blank

I see! Thank you so much for pointing that out. 

I am closing the issue then.
