### ISSUE TITLE
[Fix] Hand Wave Resize

### ISSUE THREAD

**Issue by Eshan-Sharma** [FahimFBA/FahimFBA#4]
Hi, I saw your query on EddieHub discord
I wanted to work on decreasing the size of the hand waving gif to make it inline with the text.

![unknown](https://user-images.githubusercontent.com/43044334/172007061-6c331822-87d1-42f6-8caa-5738ce10d8bd.png)

**Comment by FahimFBA** [comment]
Thanks a lot for the contribution, @Eshan-Sharma. 😊
