### ISSUE TITLE
Create a Journey

### ISSUE THREAD

**Issue by KendallDoesCoding** [FahimFBA/FahimFBA#9]
hey Fahim,

I've been helping create a product called Journey Book - A Place where coders can share their journey.

By sharing your journey, you help inspire people getting into coding, open source, etc. You got a lot of experience in coding, as per what I see from your profile, Fahim so you will really really be able to help people out.

Please create your journey at [https://github.com/collab-community/journey-book/tree/main/journeys](https://github.com/collab-community/journey-book/tree/main/journeys)

**Comment by FahimFBA** [comment]
Thanks for that. Yeah, I will surely create my journey there as soon as possible.

**Comment by KendallDoesCoding** [comment]
> Thanks for that. Yeah, I will surely create my journey there as soon as possible.

Welcome! I have send you a invite to the organization collab-community
